-- MySQL Script generated by MySQL Workbench
-- Mon Feb 16 20:58:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema comercio_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comercio_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comercio_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `comercio_db` ;

-- -----------------------------------------------------
-- Table `comercio_db`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercio_db`.`proveedores` (
  `cif` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT NULL,
  `nacionalidad` VARCHAR(50) NULL DEFAULT NULL,
  `representante` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`cif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comercio_db`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercio_db`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL DEFAULT 0,
  `foto` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Se guardará la ruta de la imagen, ej: img/foto1.jpg',
  `pais_procedencia` VARCHAR(50) NULL DEFAULT NULL,
  `proveedor_cif` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_productos_proveedores_idx` (`proveedor_cif` ASC),
  CONSTRAINT `fk_productos_proveedores`
    FOREIGN KEY (`proveedor_cif`)
    REFERENCES `comercio_db`.`proveedores` (`cif`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `comercio_db`.`proveedores`
-- -----------------------------------------------------
START TRANSACTION;
USE `comercio_db`;
INSERT INTO `comercio_db`.`proveedores` (`cif`, `nombre`, `direccion`, `nacionalidad`, `representante`, `email`, `telefono`) VALUES ('B12345678', 'TecnoSpain', 'C/ Madrid 1, Madrid, España', 'Española', 'Lucas', 'lucas@gmail.com', '123456789');
INSERT INTO `comercio_db`.`proveedores` (`cif`, `nombre`, `direccion`, `nacionalidad`, `representante`, `email`, `telefono`) VALUES ('A98765432', 'ChinaImp', 'Shenzen Ind, China ', 'China', 'Li Woi', 'liwoi@gmail.com', '987654321');
INSERT INTO `comercio_db`.`proveedores` (`cif`, `nombre`, `direccion`, `nacionalidad`, `representante`, `email`, `telefono`) VALUES ('B11223344', 'ComponentesAlmeria', 'C/Almeria 1, Almeria, España', 'Española', 'Carlos', 'carlos@gmail.com', '112233445');
INSERT INTO `comercio_db`.`proveedores` (`cif`, `nombre`, `direccion`, `nacionalidad`, `representante`, `email`, `telefono`) VALUES ('C23456789', 'ComponentesPedro', 'C/Jose 5, Malaga, España', 'Española', 'Pedro', 'pedro@gmail.com', '235415661');
INSERT INTO `comercio_db`.`proveedores` (`cif`, `nombre`, `direccion`, `nacionalidad`, `representante`, `email`, `telefono`) VALUES ('D34512356', 'ConductoresDiego', 'A/Principe 1, Jaen, España', 'Española', 'Diego', 'diego@gmail.com', '567235634');

COMMIT;


-- -----------------------------------------------------
-- Data for table `comercio_db`.`productos`
-- -----------------------------------------------------
START TRANSACTION;
USE `comercio_db`;
INSERT INTO `comercio_db`.`productos` (`id_producto`, `nombre`, `descripcion`, `precio`, `stock`, `foto`, `pais_procedencia`, `proveedor_cif`) VALUES (1, 'Monitor 24 pulgadas', 'Monitor', 120, 5, NULL, 'China', 'A98765432');
INSERT INTO `comercio_db`.`productos` (`id_producto`, `nombre`, `descripcion`, `precio`, `stock`, `foto`, `pais_procedencia`, `proveedor_cif`) VALUES (2, 'Teclado mecanico', 'mecanico', 100, 10, NULL, 'China', 'A98765432');
INSERT INTO `comercio_db`.`productos` (`id_producto`, `nombre`, `descripcion`, `precio`, `stock`, `foto`, `pais_procedencia`, `proveedor_cif`) VALUES (3, 'Raton ergonomico', 'Raton', 30, 15, NULL, 'España', 'B12345678');
INSERT INTO `comercio_db`.`productos` (`id_producto`, `nombre`, `descripcion`, `precio`, `stock`, `foto`, `pais_procedencia`, `proveedor_cif`) VALUES (4, 'Torre ATX', 'Torre', 50, 20, NULL, 'España', 'C23456789');
INSERT INTO `comercio_db`.`productos` (`id_producto`, `nombre`, `descripcion`, `precio`, `stock`, `foto`, `pais_procedencia`, `proveedor_cif`) VALUES (5, 'Placa Base ATX', 'placa base', 100, 30, NULL, 'España', 'D34512356');

COMMIT;

